### ISSUE TITLE
Feat: Add Opacity Classes

### ISSUE THREAD

**Issue by NickDJM** [coldfrontlabs/bootstrap-scss-plugins#26]
Some times we need to change the opacity of objects. Having a class for this would be super convenient.

## Solution

Have a classes like [width is in base bootstrap](https://getbootstrap.com/docs/4.2/utilities/sizing/) where we would just use `.o-25`, `.o-50`, etc. 

We can use `opacity: x` for all modern browsers and `filter: alpha(opacity=x)` for IE 8 and below.

### Mixin
```scss
@mixin opacity-variant ($parent, $value) {
  $percent: $value / 100;

  #{$parent}-#{$value} {
    opacity: $percent;
    filter: alpha(opacity=$value);
  }
}
```

### Utility

```scss
@include opacity-variant('.o', 0);
@include opacity-variant('.o', 25);
@include opacity-variant('.o', 50);
@include opacity-variant('.o', 75);
@include opacity-variant('.o', 100);
```

## Alternatives

Fully spell out the class to be more descriptive: `.opacity-25`
