### ISSUE TITLE
Feat: Transparent Background Colours

### ISSUE THREAD

**Issue by NickDJM** [coldfrontlabs/bootstrap-scss-plugins#27]
Having the ability to set background colours to be semi-transparent would be super useful.

e.x. A card overlay where you would like to have a coloured block behind the text, but still see the image behind it.

## Solution
The class should match the existing background classes: `.bg-primary`, but then add on an opacity value.

Should probably have set intervals of 10 (may be able to customize the intervals).

- `.bg-primary-10`: 10% opacity
- `.bg-primary-20`: 20% opacity
- `.bg-primary-30`: 30% opacity
- ...
- `bg-primary-90`: 90% opacity

No need for 0 or 100 as those are already covered in base bootstrap.

```scss
@each $colour, $hex in $theme-colors {
  @for $x from 1 to 9 {
    $num: $x * 10;

    .bg-#{$name}-#{$num} {
      $value: $x / 10;

      background-color: rgba($hex, $value);
    }
  }
}
```
