### ISSUE TITLE
Bug: Text shadow displays incorrectly

### ISSUE THREAD

**Issue by NickDJM** [coldfrontlabs/bootstrap-scss-plugins#39]
## Summary

When using the `.text-shadow` classes, the display looks offset.

## Expected Behaviour

Shadow should have a uniform width around the text.

## Screenshots

![Screen Shot 2019-03-12 at 2 56 54 PM](https://user-images.githubusercontent.com/6486142/54227819-215e5b00-44d7-11e9-9417-9a7e1458eae3.png)

## Additional context

This should fix the issue:

```scss
@mixin text-outline-variant ($parent, $colour, $width) {
  $negative-width: -#{$width};

  #{$parent} {
    text-shadow:
    $negative-width $negative-width 0 $colour,
    $width $negative-width 0 $colour,
    $negative-width $width 0 $colour,
    $width $width 0 $colour !important;
  }
}
```
